### ISSUE TITLE
metadata.json Reliability

### ISSUE THREAD

**Issue by AngelMunoz** [shoelace-style/react-generator#1]
Hey there! sorry to bother

> tldr; Is it safe to assume that properties always have the same fields declared? e.g. a property object in the properties array will always have 
> ```ts
> {  name: string;
>    type: string
>    values?:  string array
>    defaultValue: any | undefined  
>  }
> ```
> these properties and a similar case with the other properties array objects?

I was working on a few wrappers around Shoelace for [Sutil](https://github.com/davedawkins/Sutil) which is a DSL written in F# to write svelte applications in (you guessed it...) F#

I was doing the work by hand and I was almost [half way through](https://github.com/AngelMunoz/SutilWebComponents/issues/2) when I found out this repo and saw that you're using a `metadata.json` file to generate the React version of the shoelace package this gives me a new perspective and I could be generating the files rather than doing them by hand.

F# is a little bit more strict with types and will break when deserializing files if they have or not properties declared in a record
so

 Is it safe to assume that properties always have the same fields declared? e.g. a property object in the properties array will always have 
```ts
{  name: string;
    type: string
    values?:  string array // I'm concious it might not come
    defaultValue: any | undefined  
  }
 ```
rather than 
```
{  name: string;
    type: string
    values?:  string array
  }
```
 and a similar case with the other properties array objects?

I'll be prototyping something following more-less this repo's behavior but it would be nice to know so I can make some decisions

In any case thanks for Shoelace! it's a pretty cool library I really like it!

**Comment by claviska** [comment]
The metadata file is consistent. It’s generated here if you want to take a look.

https://github.com/shoelace-style/shoelace/blob/next/scripts/make-metadata.cjs

It’s a custom analyzer that uses TypeDoc and then massages its output into a simpler format. The process is a bit heavy, but it works.

I’ve been casually looking around for another analyzer that’s faster and lighter. I’m sure the format of metadata.json will change once I find one, but there are no immediate plans.

I can say for sure that there will always be a metadata file similar to this, or at least an easy way to access component data.

**Comment by AngelMunoz** [comment]
that's perfect! thank you I'll close this then
